services:
  - type: web
    name: vit-bfhl-api
    env: node
    region: oregon  # or choose closest region
    plan: free
    branch: main
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
